apiVersion: v1
kind: Service
metadata:
  name: wahadlo-odwrocone
spec:
  selector:
    app: wahadlo-odwrocone-regulator
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: NodePort
