apiVersion: v1
kind: ConfigMap
metadata:
  name: dwa-zbiorniki-config
  labels:
    app: dwa-zbiorniki-regulator
    updated: 20251106-110404
data:
  parametry.json: "{\n  \"regulator\": \"regulator_pd\",\n  \"metoda\": \"ziegler_nichols\"\
    ,\n  \"parametry\": {\n    \"Kp\": 1.2,\n    \"Ti\": null,\n    \"Td\": 3.12\n\
    \  }\n}"
